export const LIST_PRODUCTS_TYPES = {
    LIST_PRODUCTS_START: "LIST_PRODUCTS_START",
    LIST_PRODUCTS_SUCCESS: "LIST_PRODUCTS_SUCCESS",
    LIST_PRODUCTS_ERROR: "LIST_PRODUCTS_ERROR",
    LIST_PRODUCTS_STOP:  "LIST_PRODUCTS_STOP"
}

export const ADD_PRODUCT_TYPES = {
    ADD_PRODUCT_START: "ADD_PRODUCT_START",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
    ADD_PRODUCT_STOP:  "ADD_PRODUCT_STOP"
}

export const DELETE_PRODUCTS_TYPES = {
    DELETE_PRODUCTS_START: "DELETE_PRODUCTS_START",
    DELETE_PRODUCTS_SUCCESS: "DELETE_PRODUCTS_SUCCESS",
    DELETE_PRODUCTS_ERROR: "DELETE_PRODUCTS_ERROR",
    DELETE_PRODUCTS_STOP:  "DELETE_PRODUCTS_STOP"
}

export const VALIDATE_FIELD_TYPES = {
    VALIDATE_FIELD_START: "VALIDATE_FIELD_START",
    VALIDATE_FIELD_SUCCESS: "VALIDATE_FIELD_SUCCESS",
    VALIDATE_FIELD_ERROR: "VALIDATE_FIELD_ERROR",
    VALIDATE_FIELD_STOP:  "VALIDATE_FIELD_STOP"
}
